spring:
  application:
    name: calendar-enrichment-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydatabase}
    username: ${POSTGRES_USER:myuser}
    password: ${POSTGRES_PASSWORD:secret}
  jpa:
    show-sql: false
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: calendar_enrichment
  liquibase:
    default-schema: calendar_enrichment
    liquibase-schema: public
    parameters:
      default-schema-prefix: calendar_enrichment.
    database-change-log-table: calendar_enrichment_log
    database-change-log-lock-table: calendar_enrichment_lock
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

calendar:
  api:
    base-url: ${CALENDAR_API_BASE_URL:https://app.usergems.com/api/hiring/calendar-challenge}
    api-keys:
      stephan@usergems.com: ${API_KEY_STEPHAN:7SS16U^PmxkdVJlb^}
      kieran@usergems.com: ${API_KEY_KIERAN:vJy8I3nwriNW*I4w^}
      jas@usergems.com: ${API_KEY_JAS:tK7U8PVeGi3pP9tB^}
      josh@algolia.com: ${API_KEY_JOSH:b8R*41QR21N5wuww^}
    feign:
      logger-level: ${FEIGN_LOGGER_LEVEL:FULL}

logging:
  level:
    root: INFO
    rs.usergems: DEBUG
    rs.usergems.calendar.enrichment.client.rs.usergems.calendar.enrichment.client.calendar.CalendarFeignClient: DEBUG
  pattern:
    console: '%black(%d{ISO8601}) %highlight(%-5level) [%blue(%t)] %yellow(%C{1}): %msg%n%throwable'